<?php
$TEAM_MEMBERS_LIST = [
  ['slug' => 'kehinde-bamiwola', 'name' => 'K. H Bamiwola Esq.', 'image' => 'assets/images/bamiwola.png', 'title' => 'Managing/Principal Partner', 'practice_areas' => ['Labour Law', 'Commercial & Corporate Law', 'Property Law', 'Chieftaincy Matters', 'Intellectual Property Law']],
  ['slug' => 'oluwaseyi-odewole', 'name' => 'Oluwaseyi Odewole Esq.', 'image' => 'assets/images/head-chambers.jpeg', 'title' => 'Head of Chambers', 'practice_areas' => ['Criminal Law & Litigation', 'Civil Litigation', 'Real Estate', 'Corporate Law', 'Family Law', 'Labour Law', 'Telecommunications (Mast Management)']],
  ['slug' => 'alejo-nimotallahi', 'name' => 'Alejo Nimotallahi Aderoju, AICMC Esq.', 'image' => 'assets/images/deputy-head-chamber.jpeg', 'title' => 'Deputy Head of Chambers', 'practice_areas' => ['Labour and Employment Matters', 'Corporate Law Practice', 'Commercial Dispute Resolution', 'Litigation']],
  ['slug' => 'morakinyo-victoria', 'name' => 'Morakinyo, Victoria Afolake, AICMC Esq.', 'image' => 'assets/images/associate-partner-1.jpeg', 'title' => 'Snr. Associate Partner', 'practice_areas' => ['Labour and Employment Matters', 'Litigation', 'Legal Research', 'Corporate Law Practice', 'Dispute Resolution']],
  ['slug' => 'akinyemi-mujidat', 'name' => 'Akinyemi, Mujidat Opeyemi Esq.', 'image' => 'assets/images/associate-partner-2.jpeg', 'title' => 'Associate Partner', 'practice_areas' => ['Litigation', 'Legal Research & Advocacy', 'Commercial Law', 'Family Law', 'Labour Law', 'Contentious Matters']],
  ['slug' => 'tawakalitu-adiatu', 'name' => 'Tawakalitu Iyabode Adiatu Esq.', 'image' => 'assets/images/associate-partner-3.jpeg', 'title' => 'Associate Partner', 'practice_areas' => ['Criminal Law', 'Civil Litigation', 'Real Estate Law', 'Family Law', 'Law of Contract', 'Law of Evidence', 'Litigation Support', 'Legal Research & Drafting']],
  ['slug' => 'oluseyi-shadare', 'name' => 'Prof. Oluseyi Shadare', 'image' => 'assets/images/consultant-1.png', 'title' => 'Consultant', 'practice_areas' => ['Human Rights', 'Labour Law & Public Policy', 'Commercial & Corporate Law', 'Employment Relations']],
  ['slug' => 'bamisaye-olutola', 'name' => 'Dr. Bamisaye Olutola', 'image' => 'assets/images/consultant-2.png', 'title' => 'Consultant', 'practice_areas' => ['Human Rights', 'Litigation & Arbitration', 'Commercial & Corporate Law']],
];
